---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "joal.fullname" . }}-config
  labels:
    {{- include "joal.labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
data:
  default-1.0.0.client: |-
    {
        "keyGenerator": {
            "algorithm": {
                "type": "DIGIT_RANGE_TRANSFORMED_TO_HEX_WITHOUT_LEADING_ZEROES",
                "inclusiveLowerBound": 1,
                "inclusiveUpperBound": 4294967295
            },
            "refreshOn": "NEVER",
            "keyCase": "lower"
        },
        "peerIdGenerator": {
            "algorithm": {
                "type": "RANDOM_POOL_WITH_CHECKSUM",
                "prefix": "-TR4050-",
                "charactersPool": "0123456789abcdefghijklmnopqrstuvwxyz",
                "base": 36
            },
            "refreshOn": "TORRENT_VOLATILE",
            "shouldUrlEncode": false
        },
        "urlEncoder": {
            "encodingExclusionPattern": "[A-Za-z0-9-]",
            "encodedHexCase": "lower"
        },
        "query": "info_hash={infohash}&peer_id={peerid}&port={port}&uploaded={uploaded}&downloaded={downloaded}&left={left}&numwant={numwant}&key={key}&compact=1&supportcrypto=1&event={event}&ipv6={ipv6}",
        "numwant": 80,
        "numwantOnStop": 0,
        "requestHeaders": [
            { "name": "User-Agent", "value": "Transmission/4.0.5" },
            { "name": "Accept", "value": "*/*" },
            { "name": "Accept-Encoding", "value": "deflate, gzip" }
        ]
    }
  config.json: |-
    {
      "minUploadRate": {{ int .Values.config.minUploadRate | default 500 }},
      "maxUploadRate": {{ int .Values.config.maxUploadRate | default 15000}},
      "simultaneousSeed": {{ int .Values.config.simultaneousSeed | default 5 }},
      "client": "default-1.0.0.client",
      "keepTorrentWithZeroLeechers": {{ .Values.config.keepTorrentWithZeroLeechers | default false }},
      "uploadRatioTarget": {{ .Values.config.uploadRatioTarget | default -1 }}
    }

