---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "joal.fullname" . }}-init-scripts
  labels:
    {{- include "joal.labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
data:
{{- $specpath := printf "resources/scripts/*.sh" }}
{{- range $path, $bytes := .Files.Glob $specpath }}
  {{ regexReplaceAll "(.*)/" $path "" }}: |-
{{ $.Files.Get $path | indent 4 -}}
{{- end }}
