apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "joal.fullname" . }}
  labels:
    {{- include "joal.labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "joal.selectorLabels" (dict "context" . "name" .Values.name) | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "joal.labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cm-config.yaml") . | sha256sum }}
        checksum/init-scripts: {{ include (print $.Template.BasePath "/cm-init-scripts.yaml") . | sha256sum }}
      {{- with .Values.annotations }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      volumes:
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 6}}
      {{- end }}
      - name: {{ template "joal.fullname" . }}-init-scripts
        configMap:
          defaultMode: 493
          items:
            - key: prepare.sh
              path: prepare.sh
          name: {{ template "joal.fullname" . }}-init-scripts
      - name: {{ template "joal.fullname" . }}-config
        configMap:
          defaultMode: 493
          items:
            - key: default-1.0.0.client
              path: default-1.0.0.client
            - key: config.json
              path: config.json
          name: {{ template "joal.fullname" . }}-config
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: prepare-joal
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - /scripts/prepare.sh
          volumeMounts:
            - name: {{ template "joal.fullname" . }}-init-scripts
              mountPath: /scripts
            - name: {{ template "joal.fullname" . }}-config
              mountPath: /temp
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: JOAL_CONF
              value: "/data"
            - name: TEMP_STORAGE
              value: "/temp"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default (include "joal.defaultTag" .) .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: SPRING_MAIN_WEB_ENVIRONMENT
              value: "true"
            - name: SERVER_PORT
              value: {{ (.Values.containerPorts.http | default "9095") | quote }}
            - name: JOAL_CONF
              value: "/data"
            - name: JOAL_UI_PATH_PREFIX
              value: {{ .Values.config.joalUiPathPrefix | default (randAlphaNum 25 | quote) }}
            - name: JOAL_UI_SECRET_TOKEN
              value: {{ .Values.config.joalUiSecretToken | default (randAlphaNum 25 | quote) }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http | default "9095" }}
              protocol: TCP
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ template "joal.fullname" . }}-init-scripts
              mountPath: /scripts
            - name: {{ template "joal.fullname" . }}-config
              mountPath: /temp
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
    {{- end }}
