apiVersion: v1
kind: Service
metadata:
  name: {{ template "joal.fullname" . }}
  labels:
    {{- include "joal.labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.containerPorts.http | default "9095" }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "joal.selectorLabels" (dict "context" . "name" .Values.name) | nindent 4 }}
